name: Generate RSS Feeds

on:
  schedule:
    - cron: '30 6 * * *'  # Türkiye saati ile 09:30 (UTC 06:30)
    - cron: '0 14 * * *'  # Türkiye saati ile 17:00 (UTC 14:00)
  workflow_dispatch:      # İstersen manuel olarak da tetikleyebilmeni sağlar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests feedgen pytz

      - name: Run Python Script
        run: python main.py

      - name: Commit and Push Feeds
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add feeds/*.xml
          git commit -m "RSS Akışları Güncellendi" || echo "Değişiklik yok, commit atlandı."
          git push
